# action.yml
name: 'Sync a Repo like subdir of another'
description: 'When you push in Repo A, this repo is copied and sync like subfolder to Repo B'
author: 'Tomas Delvechio <tomasdelvechio17+github@gmail.com'
inputs:
  github-username:
    description: 'User of github'
    required: true
  target-subdir-name:
    description: "Subdir name on target repo"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-username }}
    - ${{ inputs.target-subdir-name }}
branding:
  icon: 'git-merge'
  color: 'purple' 